# Generated by Django 4.1.2 on 2022-10-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="Country",
            new_name="country",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="Crime",
            new_name="crime",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="Description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="State",
            new_name="state",
        ),
        migrations.RemoveField(
            model_name="report",
            name="Phone_number",
        ),
    ]
