# Generated by Django 4.1.2 on 2022-10-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_country_report_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="description",
            field=models.TextField(blank=True, default=True, max_length=200, null=True),
        ),
    ]
