# Generated by Django 4.1.2 on 2022-10-09 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_report_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="country",
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name="Anonymous_report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=10)),
                ("state", models.CharField(max_length=10)),
                ("crime", models.TextField(max_length=10)),
                (
                    "description",
                    models.TextField(
                        blank=True, default=True, max_length=200, null=True
                    ),
                ),
                (
                    "proof",
                    models.FileField(default=False, upload_to="dashboard\\proof"),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
