# Generated by Django 4.1.2 on 2022-10-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_report_country_anonymous_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anonymous_report",
            name="user",
        ),
    ]
