# Generated by Django 4.1.2 on 2022-10-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_anonymous_report_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="newsletter",
            field=models.BooleanField(default=False),
        ),
    ]
